// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHflQCbzAZJwxJFMapnRJzBsLO0QfrNpA',
    appId: '1:124756389738:web:afdcc6e8e46c31ea0a3f13',
    messagingSenderId: '124756389738',
    projectId: 'titiktemu-935d1',
    authDomain: 'titiktemu-935d1.firebaseapp.com',
    storageBucket: 'titiktemu-935d1.firebasestorage.app',
    measurementId: 'G-663LSF6LL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQezgnApabjryEx8TxXcoV70dfu9tXd-I',
    appId: '1:124756389738:android:949eed36f594de870a3f13',
    messagingSenderId: '124756389738',
    projectId: 'titiktemu-935d1',
    storageBucket: 'titiktemu-935d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY5xphGHuCc8v7hFlYOWtR7vajYOJvxYk',
    appId: '1:124756389738:ios:b9e257f0430044620a3f13',
    messagingSenderId: '124756389738',
    projectId: 'titiktemu-935d1',
    storageBucket: 'titiktemu-935d1.firebasestorage.app',
    iosBundleId: 'com.example.titikTemu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY5xphGHuCc8v7hFlYOWtR7vajYOJvxYk',
    appId: '1:124756389738:ios:b9e257f0430044620a3f13',
    messagingSenderId: '124756389738',
    projectId: 'titiktemu-935d1',
    storageBucket: 'titiktemu-935d1.firebasestorage.app',
    iosBundleId: 'com.example.titikTemu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHflQCbzAZJwxJFMapnRJzBsLO0QfrNpA',
    appId: '1:124756389738:web:5b4c7e8926512a660a3f13',
    messagingSenderId: '124756389738',
    projectId: 'titiktemu-935d1',
    authDomain: 'titiktemu-935d1.firebaseapp.com',
    storageBucket: 'titiktemu-935d1.firebasestorage.app',
    measurementId: 'G-LJKW9PR2MR',
  );
}
